### ISSUE TITLE
登录bug

### ISSUE THREAD

**Issue by pxkc** [Mr-Pro/membership#2]
请问登录不上去怎么回事
![image](https://user-images.githubusercontent.com/25146086/57679363-b3145100-765d-11e9-8a84-f8b5f3f87031.png)

**Comment by Mr-Pro** [comment]
默认密码123，请确认，如果错误，请试着将 `$2a$10$7.klR/dxmxXET1kp6mGFF.yqfT.RvlmME0V6LWpDg0Hjj6QhcILOy` 字符串替换数据库中admin表的password字段值
